# Generated by Django 4.1 on 2022-10-01 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('url', models.URLField()),
                ('category', models.CharField(choices=[('MISC', 'MISC'), ('ELECTRONICS', 'ELECTRONICS'), ('TOYS', 'TOYS'), ('FASHION', 'FASHION'), ('HOME', 'HOME'), ('NO CATEGORY', 'NO CATEGORY')], default='NO CATEGORY', max_length=20)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
