# Generated by Django 4.1 on 2022-10-07 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 10, 3, 28, 535533)),
        ),
        migrations.DeleteModel(
            name='CloseListing',
        ),
    ]
